const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {Pool}=require('pg');
const PORT=process.env.PORT||3000, ROOT=__dirname, SEED=path.join(ROOT,'data','store.json');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false,max:5});
const W=["01 - أدرار","02 - الشلف","03 - الأغواط","04 - أم البواقي","05 - باتنة","06 - بجاية","07 - بسكرة","08 - بشار","09 - البليدة","10 - البويرة","11 - تمنراست","12 - تبسة","13 - تلمسان","14 - تيارت","15 - تيزي وزو","16 - الجزائر","17 - الجلفة","18 - جيجل","19 - سطيف","20 - سعيدة","21 - سكيكدة","22 - سيدي بلعباس","23 - عنابة","24 - قالمة","25 - قسنطينة","26 - المدية","27 - مستغانم","28 - المسيلة","29 - معسكر","30 - ورقلة","31 - وهران","32 - البيض","33 - إليزي","34 - برج بوعريريج","35 - بومرداس","36 - الطارف","37 - تندوف","38 - تيسمسيلت","39 - الوادي","40 - خنشلة","41 - سوق أهراس","42 - تيبازة","43 - ميلة","44 - عين الدفلى","45 - النعامة","46 - عين تموشنت","47 - غرداية","48 - غليزان","49 - تيميمون","50 - برج باجي مختار","51 - أولاد جلال","52 - بني عباس","53 - عين صالح","54 - عين قزام","55 - تقرت","56 - جانت","57 - المغير","58 - المنيعة"];
let ready=false;const sessions=new Map(),fails=new Map();
function seed(){try{return JSON.parse(fs.readFileSync(SEED,'utf8'))}catch{return {settings:{},products:[],orders:[]}}}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return s+':'+crypto.pbkdf2Sync(String(p),s,120000,32,'sha256').toString('hex')}
function okPass(p,x){if(!x)return false;const [s,h]=String(x).split(':');if(!s||!h)return false;try{return crypto.timingSafeEqual(Buffer.from(h,'hex'),Buffer.from(crypto.pbkdf2Sync(String(p),s,120000,32,'sha256').toString('hex')))}catch{return false}}
function settingsDefaults(s={}){const x={...seed().settings,...s};x.enabledWilayas=Array.isArray(x.enabledWilayas)&&x.enabledWilayas.length?x.enabledWilayas:W;x.deliveryByWilaya=x.deliveryByWilaya||{};x.deliveryHomeDefault=Number(x.deliveryHomeDefault??600);x.deliveryOfficeDefault=Number(x.deliveryOfficeDefault??500);x.currency=x.currency||'دج';x.storeName=x.storeName||'Lavéa';x.storeCity=x.storeCity||'سطيف';x.storeAddress=x.storeAddress||'الجزائر';x.announcement=x.announcement||'🚚 توصيل سريع لجميع الولايات • الدفع عند الاستلام';x.storeDescription=x.storeDescription||'اختيارات أنيقة وتجربة شراء صممت للزبون الجزائري.';x.brandTagline=x.brandTagline||'NEW COLLECTION';x.brandTitle=x.brandTitle||'علامة جزائرية تحب التفاصيل.';x.brandAbout=x.brandAbout||'Lavéa تجمع الذوق والهدايا والإكسسوارات في تجربة شراء مريحة.';x.aboutImage=x.aboutImage||x.heroImage||'images/hero.jpg';x.supportHours=x.supportHours||'يومياً • 10:00 — 22:00';x.lowStockThreshold=Number(x.lowStockThreshold??5);x.heroImage=x.heroImage||'images/hero.jpg';x.orderPrefix=x.orderPrefix||'LV';x.metaPixelId=x.metaPixelId||'';x.tiktokPixelId=x.tiktokPixelId||'';x.googleAnalyticsId=x.googleAnalyticsId||'';if(!x.adminPasswordHash)x.adminPasswordHash=hash(process.env.ADMIN_PASSWORD||'Lavea@2026');return x}
async function init(){await pool.query('CREATE TABLE IF NOT EXISTS settings(id smallint primary key,data jsonb not null)');await pool.query('CREATE TABLE IF NOT EXISTS products(id bigint primary key,data jsonb not null)');await pool.query('CREATE TABLE IF NOT EXISTS orders(id text primary key,data jsonb not null)');await pool.query('CREATE TABLE IF NOT EXISTS media(id bigserial primary key,mime text not null,data bytea not null,created_at timestamptz default now())');const q=await pool.query('SELECT 1 FROM settings WHERE id=1');if(!q.rowCount){const d=seed(),s=settingsDefaults(d.settings);await pool.query('INSERT INTO settings(id,data) VALUES(1,$1)',[s]);for(const p of d.products||[])await pool.query('INSERT INTO products(id,data) VALUES($1,$2) ON CONFLICT DO NOTHING',[Number(p.id)||Date.now(),p]);for(const o of d.orders||[])await pool.query('INSERT INTO orders(id,data) VALUES($1,$2) ON CONFLICT DO NOTHING',[String(o.id),o])}ready=true}
const body=(req,max=8e6)=>new Promise((r,j)=>{let s='';req.on('data',c=>{s+=c;if(s.length>max){req.destroy();j(Error('too large'))}});req.on('end',()=>{try{r(s?JSON.parse(s):{})}catch(e){j(e)}});req.on('error',j)});
const raw=(req,max=12e6)=>new Promise((r,j)=>{const a=[];let n=0;req.on('data',c=>{n+=c.length;if(n>max){req.destroy();j(Error('too large'));return}a.push(c)});req.on('end',()=>r(Buffer.concat(a)));req.on('error',j)});
const send=(res,c,d,t='application/json')=>{res.writeHead(c,{'Content-Type':t,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin','Content-Security-Policy':"default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob:; connect-src 'self' https:;"});res.end(t==='application/json'?JSON.stringify(d):d)};
async function S(){return (await pool.query('select data from settings where id=1')).rows[0].data}async function SP(s){await pool.query('update settings set data=$1 where id=1',[s])}async function P(){return (await pool.query('select data from products order by id desc')).rows.map(r=>r.data)}async function O(){return (await pool.query("select data from orders order by (data->>'createdAt') desc")).rows.map(r=>r.data)}
function auth(req){const x=sessions.get((req.headers.authorization||'').replace(/^Bearer\s+/,''));if(!x)return false;if(Date.now()-x>12*60*60*1000)return false;return true}
function clean(o){return {id:o.id,name:o.name,phone:o.phone,wilaya:o.wilaya,deliveryType:o.deliveryType,address:o.address,note:o.note,items:o.items,total:o.total,subtotal:o.subtotal,shipping:o.shipping,status:o.status,createdAt:o.createdAt}}
const app=http.createServer(async(req,res)=>{try{if(!ready)await init();const u=new URL(req.url,`http://${req.headers.host}`),p=u.pathname;if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*'});return res.end()}
if(p==='/api/login'&&req.method==='POST'){const b=await body(),s=await S(),ip=req.socket.remoteAddress||'x',a=(fails.get(ip)||[]).filter(t=>Date.now()-t<9e5);if(a.length>=8)return send(res,429,{error:'محاولات دخول كثيرة'});if(!okPass(b.password,s.adminPasswordHash)){a.push(Date.now());fails.set(ip,a);return send(res,401,{error:'كلمة المرور غير صحيحة'})}const t=crypto.randomBytes(32).toString('hex');sessions.set(t,Date.now());return send(res,200,{token:t})}
if(p==='/api/store'&&req.method==='GET'){const s=S?await S():{};return send(res,200,{settings:s,products:await P(),delivery:W.map(w=>({wilaya:w,enabled:s.enabledWilayas.includes(w),home:s.deliveryByWilaya[w]?.home??s.deliveryHomeDefault,office:s.deliveryByWilaya[w]?.office??s.deliveryOfficeDefault}))})}
if(p.startsWith('/api/media/')&&req.method==='GET'){const id=Number(p.split('/').pop()),q=await pool.query('select mime,data from media where id=$1',[id]);if(!q.rowCount)return send(res,404,{error:'not found'});res.writeHead(200,{'Content-Type':q.rows[0].mime,'Cache-Control':'public,max-age=31536000,immutable'});return res.end(q.rows[0].data)}
if(p==='/api/orders'&&req.method==='POST'){const b=await body(),s=await S(),ps=await P();if(!b.name||!b.phone||!b.wilaya||!b.deliveryType||!b.address||!Array.isArray(b.items)||!b.items.length)return send(res,400,{error:'معلومات الطلب ناقصة'});const phone=String(b.phone).replace(/\s/g,'');if(!/^0[567][0-9]{8}$/.test(phone))return send(res,400,{error:'رقم الهاتف غير صالح'});if(!s.enabledWilayas.includes(b.wilaya))return send(res,400,{error:'التوصيل غير متاح'});const key=b.deliveryType==='home'?'home':'office',shipping=Number(s.deliveryByWilaya[b.wilaya]?.[key]??(key==='home'?s.deliveryHomeDefault:s.deliveryOfficeDefault));const items=b.items.map(i=>{const p=ps.find(x=>String(x.id)===String(i.id));return {id:p?.id??i.id,name:p?.name??i.name,price:Number(p?.price??i.price)||0,quantity:Math.max(1,Number(i.quantity)||1)}});const subtotal=items.reduce((n,i)=>n+i.price*i.quantity,0),order={id:'LV-'+Date.now().toString(36).toUpperCase(),name:b.name.trim(),phone,wilaya:b.wilaya,deliveryType:key,address:b.address.trim(),note:String(b.note||'').trim(),items,subtotal,shipping,total:subtotal+shipping,status:'جديد',createdAt:new Date().toISOString()};await pool.query('insert into orders(id,data) values($1,$2)',[order.id,order]);for(const i of items)await pool.query("update products set data=jsonb_set(data,'{stock}',to_jsonb(greatest(0,coalesce((data->>'stock')::int,0)-$1)),true) where id=$2",[i.quantity,Number(i.id)]);return send(res,201,{order:clean(order)})}
if(p.startsWith('/api/')&&!auth(req))return send(res,401,{error:'غير مصرح'});
if(p==='/api/admin/products'&&req.method==='GET')return send(res,200,await P());
if(p==='/api/admin/products'&&req.method==='POST'){const b=await body();if(!String(b.name||'').trim())return send(res,400,{error:'اسم المنتج مطلوب'});const pr={...b,id:Date.now(),name:String(b.name).trim(),price:Math.max(0,Number(b.price)||0),oldPrice:Math.max(0,Number(b.oldPrice)||0),stock:Math.max(0,Number(b.stock)||0),rating:Number(b.rating)||5,active:b.active!==false,landingEnabled:b.landingEnabled!==false,slug:b.slug||Date.now().toString()};await pool.query('insert into products(id,data) values($1,$2)',[pr.id,pr]);return send(res,201,pr)}
if(p.startsWith('/api/admin/products/')&&req.method==='PUT'){const id=Number(p.split('/').pop()),ps=await P(),cur=ps.find(x=>x.id===id);if(!cur)return send(res,404,{error:'المنتج غير موجود'});const b=await body(),pr={...cur,...b,id,price:Math.max(0,Number(b.price??cur.price)||0),oldPrice:Math.max(0,Number(b.oldPrice??cur.oldPrice)||0),stock:Math.max(0,Number(b.stock??cur.stock)||0)};await pool.query('update products set data=$1 where id=$2',[pr,id]);return send(res,200,pr)}
if(p.startsWith('/api/admin/products/')&&req.method==='DELETE'){await pool.query('delete from products where id=$1',[Number(p.split('/').pop())]);return send(res,200,{ok:true})}
if(p==='/api/admin/settings'&&req.method==='PUT'){const b=await body(),s={...(await S()),...b};if(Array.isArray(b.enabledWilayas))s.enabledWilayas=b.enabledWilayas;if(b.deliveryByWilaya)s.deliveryByWilaya=b.deliveryByWilaya;await SP(s);return send(res,200,s)}
if(p==='/api/admin/orders'&&req.method==='GET')return send(res,200,(await O()).map(clean));
if(p.startsWith('/api/admin/orders/')&&req.method==='PUT'){const id=p.split('/').pop(),b=await body(),q=await pool.query("update orders set data=jsonb_set(data,'{status}',to_jsonb($1::text),true) where id=$2 returning data",[String(b.status||'جديد'),id]);if(!q.rowCount)return send(res,404,{error:'الطلب غير موجود'});return send(res,200,clean(q.rows[0].data))}
if(p==='/api/admin/password'&&req.method==='PUT'){const b=await body(),s=await S();if(String(b.newPassword||'').length<8)return send(res,400,{error:'8 أحرف على الأقل'});if(!okPass(b.currentPassword,s.adminPasswordHash))return send(res,401,{error:'كلمة المرور الحالية غير صحيحة'});s.adminPasswordHash=hash(b.newPassword);await SP(s);sessions.clear();return send(res,200,{ok:true})}
if(p==='/api/admin/upload'&&req.method==='POST'){const ct=req.headers['content-type']||'';if(!/^image\/(jpeg|png|webp|gif|avif)$/.test(ct))return send(res,400,{error:'صورة غير مدعومة'});const buf=await raw(req);const q=await pool.query('insert into media(mime,data) values($1,$2) returning id',[ct,buf]);return send(res,201,{url:'/api/media/'+q.rows[0].id})}
if(p==='/api/admin/export'&&req.method==='GET')return send(res,200,{exportedAt:new Date().toISOString(),settings:await S(),products:await P(),orders:await O()});
let f=p==='/'?'/index.html':p;if(f==='/admin')f='/admin.html';const fp=path.normalize(path.join(ROOT,f));if(!fp.startsWith(ROOT))return send(res,403,{error:'forbidden'});fs.readFile(fp,(e,d)=>{if(e)return send(res,404,{error:'not found'});const ext=path.extname(fp),m={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.gif':'image/gif','.avif':'image/avif','.svg':'image/svg+xml'};send(res,200,d,m[ext]||'application/octet-stream')})
}catch(e){console.error(e);send(res,500,{error:'حدث خطأ في الخادم'})}});
init().then(()=>app.listen(PORT,()=>console.log('Lavéa on '+PORT))).catch(e=>{console.error(e);process.exit(1)});