let token=localStorage.getItem('lavea_admin_token')||'',db={settings:{},products:[],delivery:[],orders:[]};
const $=id=>document.getElementById(id);const money=n=>`${Number(n||0).toLocaleString('fr-DZ')} ${db.settings.currency||'دج'}`;
let notificationItems=[],knownOrderIds=new Set(),pollTimer=null;
async function api(path,opt={}){const headers={'Content-Type':'application/json',Authorization:'Bearer '+token,...(opt.headers||{})};const r=await fetch(path,{...opt,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'حدث خطأ');return d}
async function login(){const msg=$('loginMsg');msg.textContent='';try{const d=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('password').value})});const x=await d.json();if(!d.ok)throw Error(x.error);token=x.token;localStorage.setItem('lavea_admin_token',token);showPanel();await load(true);startPolling()}catch(e){msg.textContent=e.message}}
function logout(){stopPolling();localStorage.removeItem('lavea_admin_token');location.reload()}
function showPanel(){$('login').hidden=true;$('panel').hidden=false}
async function load(showToast=false){try{const fresh=await api('/api/store');const orders=await api('/api/admin/orders');db={...fresh,orders};window.ordersCache=orders;renderAll();buildNotifications(orders);if(showToast)toast('تم تحديث البيانات ✓')}catch(e){if(e.message==='غير مصرح'){logout();return}toast(e.message)}}
function startPolling(){stopPolling();pollTimer=setInterval(async()=>{try{const orders=await api('/api/admin/orders');const oldCount=knownOrderIds.size;const oldIds=new Set(knownOrderIds);db.orders=orders;window.ordersCache=orders;const newOrders=orders.filter(o=>!oldIds.has(o.id));newOrders.forEach(o=>pushNotification({id:'order-'+o.id,type:'order',title:'طلب جديد',text:`${o.name} • ${money(o.total)}`,createdAt:o.createdAt,unread:true}));knownOrderIds=new Set(orders.map(o=>o.id));if(newOrders.length){renderDashboard();renderOrders();renderCustomersFromOrders();updateNotificationUI();newOrders.forEach(showBrowserOrderNotification)}}catch{}} ,30000)}
function stopPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
function renderAll(){renderDashboard();renderProducts();renderDelivery();renderOrders();fillSettings();renderCustomersFromOrders();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('topStoreName').textContent=db.settings.storeName||'متجر الأناقة';knownOrderIds=new Set((db.orders||[]).map(o=>o.id))}
function switchTab(t){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));document.querySelectorAll('.tabpane').forEach(x=>x.classList.toggle('active',x.id===t));closeNotifications();closeAdminNav();window.scrollTo({top:0,behavior:'smooth'})}
function renderDashboard(){const orders=db.orders||[],valid=orders.filter(o=>o.status!=='ملغى'),sales=valid.reduce((s,o)=>s+Number(o.total||0),0),stock=db.products.reduce((s,p)=>s+Number(p.stock||0),0),low=db.products.filter(p=>Number(p.stock||0)<=Number(db.settings.lowStockThreshold??5));$('sOrders').textContent=orders.length;$('sSales').textContent=money(sales);$('sProducts').textContent=db.products.length;$('sStock').textContent=stock;$('sOrdersHint').textContent=`${orders.filter(o=>o.status==='جديد').length} طلبات جديدة`;$('sActiveHint').textContent=`${db.products.filter(p=>p.active!==false).length} ظاهرة`;$('sLowHint').textContent=low.length?`${low.length} مخزون منخفض`:'المخزون جيد';$('sideOrdersBadge').hidden=!orders.filter(o=>o.status==='جديد').length;$('sideOrdersBadge').textContent=orders.filter(o=>o.status==='جديد').length;$('recentOrders').innerHTML=orders.slice(0,6).map(o=>`<div class="order-mini"><b>${esc(o.id)}</b><span>${esc(o.name)}</span><span>${money(o.total)}</span><span class="status-pill">${esc(o.status||'جديد')}</span></div>`).join('')||'<div class="notification-empty">لا توجد طلبات بعد.</div>';renderHealth();renderActivity()}
function renderHealth(){const low=db.products.filter(p=>Number(p.stock||0)<=Number(db.settings.lowStockThreshold??5)),inactive=db.products.filter(p=>p.active===false),missing=['phone','whatsapp','storeCity'].filter(k=>!String(db.settings[k]||'').trim());const rows=[];rows.push(`<div class="health-row"><i class="fa-solid fa-circle-check"></i><span>المتجر متصل ويستقبل الطلبات</span></div>`);rows.push(`<div class="health-row"><i class="fa-solid ${low.length?'fa-triangle-exclamation':'fa-circle-check'}"></i><span>${low.length?`${low.length} منتج بمخزون منخفض`:'لا توجد منتجات منخفضة المخزون'}<small>${low.length?'راجع قسم المنتجات':'كل شيء جيد'}</small></span></div>`);if(inactive.length)rows.push(`<div class="health-row"><i class="fa-solid fa-eye-slash"></i><span>${inactive.length} منتج مخفي<small>يمكنك مراجعته من المنتجات</small></span></div>`);if(missing.length)rows.push(`<div class="health-row"><i class="fa-solid fa-circle-exclamation"></i><span>بعض بيانات التواصل ناقصة<small>أكمل إعدادات المتجر</small></span></div>`);$('healthList').innerHTML=rows.join('')}
function renderActivity(){const items=[];(db.orders||[]).slice(0,4).forEach(o=>items.push(`<div class="activity-row"><i class="fa-solid fa-bag-shopping"></i><span><b>${esc(o.name)}</b><small>طلب ${esc(o.id)} • ${timeAgo(o.createdAt)}</small></span></div>`));if(!items.length)items.push('<div class="notification-empty">لا يوجد نشاط بعد.</div>');$('activityList').innerHTML=items.join('')}
function renderProducts(){const q=String($('productSearch')?.value||'').toLowerCase().trim(),f=$('productFilter')?.value||'all',threshold=Number(db.settings.lowStockThreshold??5);let list=db.products.filter(p=>{const match=!q||String(p.name||'').toLowerCase().includes(q)||String(p.category||'').toLowerCase().includes(q);const filter=f==='active'?p.active!==false:f==='hidden'?p.active===false:f==='low'?Number(p.stock||0)<=threshold:true;return match&&filter});$('productList').innerHTML=list.map(p=>`<article class="p-card"><img src="${esc(p.image||'images/hero.jpg')}" alt="${esc(p.name)}" loading="lazy"><div class="p-card-body"><small>${esc(p.category||'بدون فئة')}</small><h3>${esc(p.name)}</h3><div class="p-card-price">${money(p.price)}</div><div class="p-card-meta"><span>المخزون: ${Number(p.stock||0)}</span><span>★ ${Number(p.rating||5).toFixed(1)}</span></div><div class="p-card-actions"><button onclick="editProduct(${p.id})"><i class="fa-solid fa-pen"></i> تعديل</button><button class="danger" onclick="deleteProduct(${p.id})"><i class="fa-solid fa-trash"></i> حذف</button><a class="success" href="?product=${encodeURIComponent(p.slug||p.id)}" target="_blank"><i class="fa-solid fa-eye"></i> عرض</a></div></div></article>`).join('')||'<div class="card"><b>لا توجد نتائج.</b><p>جرّب كلمة بحث أخرى أو غيّر الفلتر.</p></div>'}
function renderDelivery(){$('defaultHome').value=db.settings.deliveryHomeDefault||0;$('defaultOffice').value=db.settings.deliveryOfficeDefault||0;$('deliveryRows').innerHTML=(db.delivery||[]).map((d,i)=>`<tr><td><b>${esc(d.wilaya)}</b></td><td><input type="checkbox" data-i="${i}" class="den" ${d.enabled?'checked':''}></td><td><input type="number" min="0" data-i="${i}" class="dh" value="${Number(d.home)||0}"></td><td><input type="number" min="0" data-i="${i}" class="do" value="${Number(d.office)||0}"></td></tr>`).join('')}
function renderOrders(){const q=String($('orderSearch')?.value||'').toLowerCase().trim(),f=$('orderStatusFilter')?.value||'all';const list=(db.orders||[]).filter(o=>{const match=!q||[o.id,o.name,o.phone,o.wilaya].some(v=>String(v||'').toLowerCase().includes(q));return match&&(f==='all'||o.status===f)});$('orderRows').innerHTML=list.map(o=>`<article class="card order-card"><div class="order-main"><div class="order-id">${esc(o.id)}<small>${timeAgo(o.createdAt)}</small></div><div class="order-customer"><b>${esc(o.name)}</b><small>${esc(o.phone)}</small></div><div class="order-meta"><b>${esc(o.wilaya)}</b><small>${o.deliveryType==='home'?'🏠 منزل':'🏢 مكتب'}</small></div><div class="order-total"><b>${money(o.total)}</b><small>${(o.items||[]).length} منتجات</small></div></div><div class="order-status"><select onchange="changeStatus('${escAttr(o.id)}',this.value)">${['جديد','مؤكد','قيد الشحن','تم التسليم','ملغى'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></div></article>`).join('')||'<div class="card notification-empty">لا توجد طلبات مطابقة.</div>'}
function fillSettings(){const s=db.settings||{};[['metaPixelId',s.metaPixelId],['tiktokPixelId',s.tiktokPixelId],['googleAnalyticsId',s.googleAnalyticsId],['storeName',s.storeName],['phone',s.phone],['whatsapp',s.whatsapp],['announcement',s.announcement],['heroImage',s.heroImage||'images/hero.jpg'],['storeDescription',s.storeDescription],['storeEmail',s.email],['storeCity',s.storeCity],['storeAddress',s.storeAddress],['storeMap',s.storeMap],['instagram',s.instagram],['facebook',s.facebook],['orderPrefix',s.orderPrefix||'LV'],['lowStockThreshold',s.lowStockThreshold??5]].forEach(([id,v])=>{if($(id))$(id).value=v??''})}
function newProduct(){openProduct({id:'',name:'',category:'هدايا',price:0,oldPrice:0,stock:0,rating:5,slug:'',image:'',description:'',longDescription:'',landingHeadline:'',landingSubheadline:'',active:true,landingEnabled:true})}
function editProduct(id){const p=db.products.find(x=>x.id===id);if(p)openProduct(p)}
function openProduct(p){$('productModal').classList.add('show');$('productModal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open');$('modalTitle').textContent=p.id?'تعديل المنتج':'إضافة منتج';$('pId').value=p.id;$('pName').value=p.name||'';$('pCategory').value=p.category||'';$('pPrice').value=p.price||0;$('pOldPrice').value=p.oldPrice||0;$('pStock').value=p.stock||0;$('pRating').value=p.rating||5;$('pSlug').value=p.slug||'';$('pImage').value=p.image||'';$('pDesc').value=p.description||'';$('pLong').value=p.longDescription||'';$('pHeadline').value=p.landingHeadline||'';$('pSub').value=p.landingSubheadline||'';$('pActive').checked=p.active!==false;$('pLanding').checked=p.landingEnabled!==false;setTimeout(()=>$('pName').focus(),50)}
function closeModal(){$('productModal').classList.remove('show');$('productModal').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
async function saveProduct(){const name=$('pName').value.trim();if(!name)return toast('اسم المنتج مطلوب');const b={name,category:$('pCategory').value.trim(),price:Number($('pPrice').value),oldPrice:Number($('pOldPrice').value),stock:Number($('pStock').value),rating:Number($('pRating').value),slug:$('pSlug').value.trim(),image:$('pImage').value.trim(),description:$('pDesc').value.trim(),longDescription:$('pLong').value.trim(),landingHeadline:$('pHeadline').value.trim(),landingSubheadline:$('pSub').value.trim(),active:$('pActive').checked,landingEnabled:$('pLanding').checked};if(b.price<0)return toast('السعر غير صالح');try{if($('pId').value)await api('/api/admin/products/'+$('pId').value,{method:'PUT',body:JSON.stringify(b)});else await api('/api/admin/products',{method:'POST',body:JSON.stringify(b)});closeModal();await load(true);toast('تم حفظ المنتج ✓')}catch(e){toast(e.message)}}
async function deleteProduct(id){if(!confirm('حذف المنتج نهائياً؟'))return;try{await api('/api/admin/products/'+id,{method:'DELETE'});await load(true);toast('تم حذف المنتج')}catch(e){toast(e.message)}}
async function saveDelivery(){const map={};(db.delivery||[]).forEach((d,i)=>{map[d.wilaya]={home:Number(document.querySelectorAll('.dh')[i].value),office:Number(document.querySelectorAll('.do')[i].value)}});const enabled=[...document.querySelectorAll('.den')].map((x,i)=>x.checked?db.delivery[i].wilaya:null).filter(Boolean);try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({deliveryHomeDefault:Number($('defaultHome').value),deliveryOfficeDefault:Number($('defaultOffice').value),deliveryByWilaya:map,enabledWilayas:enabled})});await load();toast('تم حفظ أسعار التوصيل ✓')}catch(e){toast(e.message)}}
async function changeStatus(id,status){try{await api('/api/admin/orders/'+id,{method:'PUT',body:JSON.stringify({status})});const o=db.orders.find(x=>x.id===id);if(o)o.status=status;renderDashboard();renderOrders();buildNotifications(db.orders);toast('تم تحديث حالة الطلب ✓')}catch(e){toast(e.message)}}
async function saveMarketing(){try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({metaPixelId:$('metaPixelId').value.trim(),tiktokPixelId:$('tiktokPixelId').value.trim(),googleAnalyticsId:$('googleAnalyticsId').value.trim()})});toast('تم حفظ Pixel IDs ✓')}catch(e){toast(e.message)}}
async function saveStore(){try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({storeName:$('storeName').value.trim(),phone:$('phone').value.trim(),whatsapp:$('whatsapp').value.trim(),announcement:$('announcement').value.trim(),heroImage:$('heroImage').value.trim(),storeDescription:$('storeDescription').value.trim(),email:$('storeEmail').value.trim(),storeCity:$('storeCity').value.trim(),storeAddress:$('storeAddress').value.trim(),storeMap:$('storeMap').value.trim(),instagram:$('instagram').value.trim(),facebook:$('facebook').value.trim(),orderPrefix:$('orderPrefix').value.trim()||'LV',lowStockThreshold:Number($('lowStockThreshold').value||5)})});await load();toast('تم حفظ إعدادات المتجر ✓')}catch(e){toast(e.message)}}
async function uploadField(input,target){const f=input.files?.[0];if(!f)return;if(f.size>10*1024*1024)return toast('الصورة أكبر من 10MB');if(!f.type.startsWith('image/'))return toast('اختر ملف صورة');try{const r=await fetch('/api/admin/upload',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':f.type},body:f});const d=await r.json();if(!r.ok)throw Error(d.error);$(target).value=d.url;toast('تم رفع الصورة ✓')}catch(e){toast(e.message)}}
async function changePassword(){const currentPassword=$('currentPassword').value,newPassword=$('newPassword').value,confirmPassword=$('confirmPassword').value;if(!currentPassword||!newPassword||!confirmPassword)return toast('أكمل جميع الخانات');if(newPassword.length<8)return toast('كلمة المرور الجديدة يجب أن تكون 8 أحرف على الأقل');if(newPassword!==confirmPassword)return toast('تأكيد كلمة المرور غير مطابق');if(!confirm('هل تريد تغيير كلمة مرور لوحة الإدارة؟'))return;try{await api('/api/admin/password',{method:'PUT',body:JSON.stringify({currentPassword,newPassword})});toast('تم تغيير كلمة المرور. سيتم تسجيل الخروج.');setTimeout(logout,900)}catch(e){toast(e.message)}}
async function exportStore(){try{const d=await api('/api/admin/export');const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lavea-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);toast('تم تنزيل النسخة الاحتياطية ✓')}catch(e){toast(e.message)}}
function renderCustomersFromOrders(){const host=$('customerList');if(!host)return;const m={};(window.ordersCache||db.orders||[]).forEach(o=>{const k=o.phone||o.name||o.id;(m[k]??={name:o.name||'زبون',phone:o.phone||'',wilaya:o.wilaya||'',count:0,total:0});m[k].count++;m[k].total+=Number(o.total||0)});const vals=Object.values(m).sort((a,b)=>b.total-a.total);$('crmCount').textContent=vals.length;$('crmOrders').textContent=(db.orders||[]).length;$('crmSales').textContent=money((db.orders||[]).filter(o=>o.status!=='ملغى').reduce((s,o)=>s+Number(o.total||0),0));host.innerHTML=vals.map(c=>`<div class="customer-card"><b>${esc(c.name)}</b><span>${esc(c.phone)}</span><small>${esc(c.wilaya)} • ${c.count} طلبات • ${money(c.total)}</small></div>`).join('')||'<p>لا يوجد عملاء بعد.</p>'}
function buildNotifications(orders){notificationItems=[];const threshold=Number(db.settings.lowStockThreshold??5);orders.filter(o=>o.status==='جديد').slice(0,8).forEach(o=>notificationItems.push({id:'order-'+o.id,type:'order',title:'طلب جديد',text:`${o.name} • ${money(o.total)}`,createdAt:o.createdAt,unread:false}));db.products.filter(p=>Number(p.stock||0)<=threshold).slice(0,8).forEach(p=>notificationItems.push({id:'stock-'+p.id,type:'stock',title:'مخزون منخفض',text:`${p.name} • المتبقي ${p.stock}`,createdAt:new Date().toISOString(),unread:false}));const saved=JSON.parse(localStorage.getItem('lavea_admin_unread')||'[]');notificationItems.forEach(n=>{n.unread=saved.includes(n.id)});updateNotificationUI()}
function pushNotification(n){notificationItems.unshift(n);const saved=JSON.parse(localStorage.getItem('lavea_admin_unread')||'[]');if(!saved.includes(n.id))saved.push(n.id);localStorage.setItem('lavea_admin_unread',JSON.stringify(saved));updateNotificationUI()}
function updateNotificationUI(){const unread=notificationItems.filter(n=>n.unread).length;$('notificationCount').textContent=unread;$('notificationCount').hidden=!unread;$('notificationSubtitle').textContent=unread?`${unread} إشعارات غير مقروءة`:'آخر التنبيهات';$('notificationList').innerHTML=notificationItems.length?notificationItems.slice(0,12).map(n=>`<div class="notification-item ${n.unread?'unread':''}"><span class="notification-icon"><i class="fa-solid ${n.type==='stock'?'fa-box':'fa-bag-shopping'}"></i></span><div><b>${esc(n.title)}</b><small>${esc(n.text)} • ${timeAgo(n.createdAt)}</small></div></div>`).join(''):'<div class="notification-empty"><i class="fa-regular fa-bell"></i><br>لا توجد إشعارات حالياً</div>'}
function toggleNotifications(){const p=$('notificationPanel');p.hidden=!p.hidden;if(!p.hidden){updateNotificationUI()}}
function closeNotifications(){$('notificationPanel').hidden=true}
function markNotificationsRead(){notificationItems.forEach(n=>n.unread=false);localStorage.setItem('lavea_admin_unread','[]');updateNotificationUI();toast('تم تحديد الإشعارات كمقروءة')}
async function requestBrowserNotifications(){if(!('Notification'in window))return toast('المتصفح لا يدعم إشعارات النظام');const p=await Notification.requestPermission();toast(p==='granted'?'تم تفعيل إشعارات المتصفح ✓':p==='denied'?'تم رفض الإشعارات من المتصفح':'لم يتم تفعيل الإشعارات')}
function showBrowserOrderNotification(o){if('Notification'in window&&Notification.permission==='granted')new Notification('Lavéa — طلب جديد',{body:`${o.name} • ${money(o.total)}`})}
function toggleAdminNav(){$('adminNav')?.classList.toggle('open');document.querySelector('.admin-nav-overlay')?.classList.toggle('show')}
function closeAdminNav(){$('adminNav')?.classList.remove('open');document.querySelector('.admin-nav-overlay')?.classList.remove('show')}
function togglePassword(){const i=$('password'),icon=document.querySelector('.password-field button i');i.type=i.type==='password'?'text':'password';icon.className=i.type==='password'?'fa-solid fa-eye':'fa-solid fa-eye-slash'}
function copyPublishText(type){const texts={github:'افتح GitHub > أنشئ Repository عام > ارفع محتوى مجلد publish > Settings > Pages > Deploy from branch > main / root.',netlify:'افتح Netlify > Add new site > Deploy manually > اسحب مجلد publish إلى نافذة الرفع.',vercel:'افتح Vercel > New Project > ارفع/اربط المستودع > Deploy.'};navigator.clipboard?.writeText(texts[type]||'').then(()=>toast('تم نسخ خطوات النشر ✓')).catch(()=>toast(texts[type]||''))}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}function escAttr(s){return String(s??'').replace(/['\\]/g,'\\$&')}function timeAgo(v){if(!v)return 'الآن';const d=Date.now()-new Date(v).getTime(),m=Math.max(1,Math.floor(d/60000));if(m<60)return `منذ ${m} د`;const h=Math.floor(m/60);if(h<24)return `منذ ${h} س`;return `منذ ${Math.floor(h/24)} يوم`}function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2800)}
document.addEventListener('click',e=>{if(!$('notificationPanel')?.hidden&&!e.target.closest('#notificationPanel')&&!e.target.closest('#notificationBtn'))closeNotifications()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeNotifications();closeAdminNav()}});$('productModal').addEventListener('click',e=>{if(e.target.id==='productModal')closeModal()});
if(token){showPanel();load().then(startPolling)}
